In [3]:
import statistics

In [21]:
P = [2, 4, 4, 4, 5, 5, 7, 9]

In [5]:
statistics.mean(P)

5

In [6]:
import numpy as np

In [22]:
Q = [2, 4, 4, 4, 5, 5, 7, 9]

In [8]:
np.mean(Q)

5.0

In [9]:
np.std(P)

2.0

In [10]:
np.std(Q)

2.0

In [11]:
np.median(P)

4.5

In [12]:
np.max(P)

9

In [13]:
np.min(P)

2

In [14]:
np.percentile(P, 25)

4.0

In [15]:
np.percentile(P, 50)

4.5

In [16]:
np.percentile(P, 75)

5.5

In [17]:
np.var(Q)

4.0

In [18]:
P = [2, 4, 4, 4, 5, 5, 7, 9]
Q = [10, 13, 15, 14, 13, 16, 18, 21]

In [19]:
np.cov(P,Q)

array([[ 4.57142857,  6.85714286],
       [ 6.85714286, 11.42857143]])

In [20]:
A = [2, 4, 4, 4, 5, 5, 7, 9]
B = [10, 13, 15, 14, 13, 16, 18, 21]

In [23]:
np.cov(A,B)

array([[ 4.57142857,  6.85714286],
       [ 6.85714286, 11.42857143]])

In [24]:
np.cov(A,B)[0,]

array([4.57142857, 6.85714286])

In [25]:
np.cov(A,B)[0,0]

4.571428571428571

In [27]:
np.cov(A,B)[1,1]

11.428571428571427

In [28]:
np.corrcoef(A,B)

array([[1.       , 0.9486833],
       [0.9486833, 1.       ]])